# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('asignatura', models.CharField(max_length=50)),
                ('docente', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=50)),
            ],
        ),
    ]
